### ISSUE TITLE
On novnc-feature the BTDEX power button doesn't stop the container like on the the one with out novnc

### ISSUE THREAD

**Issue by paulpoco** [furritos/docker-btdex#9] opened 2022-03-05 03:47 UTC
On novnc-feature the BTDEX power button doesn't stop the container like on the the one with out novnc

**Comment by furritos** [comment] 2022-03-05 18:17
Well, this is now because the container is now completely different.  To accommodate BTDEX's support for opening links, I had to include a desktop which is now like a tiny VM, more-or-less.  I don't necessarily see this as an issue other than just a side-effect of just instantiating a desktop.  For now, I'll leave it as is and drop priority and will be addressed in a future build.

**Comment by furritos** [comment] 2022-03-08 07:37
For now, this issue won't be addressed.  The use-case for BTDEX requires that the application be up as much as possible as it has built-in features to do so.  In the spirit of the application, the container is configured with `supervisor` to make sure that it can self-restart when it can (and when it's not the cause of it going down in the first place).

**Closed as completed by furritos** 2022-03-08 07:37 UTC
Labels: wontfix
